import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  readonly children: React.ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          {props.children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
